# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Reference App QA - Production

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types:
      - Reff_App_Test

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Event Information
        if: github.event.action == 'Reff_App_Test'
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Compile contracts
        env:
          BLOCKCHAIN_PROVIDER_URL: ${{ secrets.BLOCKCHAIN_PROVIDER_URL }}
          REGISTRY_CONTRACT_ADDRESS: ${{ secrets.REGISTRY_CONTRACT_ADDRESS }}
        run: npm run compile
      - name: Solidity Lint
        run: npm run lint:sol
      - name: JS Lint
        run: npm run lint:ts
      - name: Run coders examples
        env:
          BLOCKCHAIN_PROVIDER_URL: ${{ secrets.BLOCKCHAIN_PROVIDER_URL }}
        run:
          npx hardhat run scripts/coders.ts
      - name: Unit tests for BSC
        env:
          BLOCKCHAIN_PROVIDER_URL: ${{ secrets.BLOCKCHAIN_PROVIDER_URL_BSC }}
          REGISTRY_CONTRACT_ADDRESS: ${{ secrets.REGISTRY_CONTRACT_ADDRESS_BSC }}
        run: npm run test
      - name: Run API Client examples for BSC
        env:
          BLOCKCHAIN_PROVIDER_URL: ${{ secrets.BLOCKCHAIN_PROVIDER_URL_BSC }}
          REGISTRY_CONTRACT_ADDRESS: ${{ secrets.REGISTRY_CONTRACT_ADDRESS_BSC }}
          API_KEY: ${{ secrets.APY_KEY_BSC }}
        run: npx hardhat run scripts/api-client.ts
      - name: Run proof verification example for BSC
        env:
          BLOCKCHAIN_PROVIDER_URL: ${{ secrets.BLOCKCHAIN_PROVIDER_URL_BSC }}
          REGISTRY_CONTRACT_ADDRESS: ${{ secrets.REGISTRY_CONTRACT_ADDRESS_BSC }}
          API_BASE_URL: ${{ secrets.API_BASE_URL_BSC }}
          API_KEY: ${{ secrets.APY_KEY_BSC }}
        run:
          npx hardhat run scripts/proof-verification.ts
      - name: Unit tests for ETH
        env:
          BLOCKCHAIN_PROVIDER_URL: ${{ secrets.BLOCKCHAIN_PROVIDER_URL }}
          REGISTRY_CONTRACT_ADDRESS: ${{ secrets.REGISTRY_CONTRACT_ADDRESS }}
        run: npm run test
      - name: Run API Client examples for ETH
        env:
          BLOCKCHAIN_PROVIDER_URL: ${{ secrets.BLOCKCHAIN_PROVIDER_URL }}
          REGISTRY_CONTRACT_ADDRESS: ${{ secrets.REGISTRY_CONTRACT_ADDRESS }}
          API_KEY: ${{ secrets.APY_KEY }}
        run: npx hardhat run scripts/api-client.ts
      - name: Run proof verification example for ETH
        env:
          BLOCKCHAIN_PROVIDER_URL: ${{ secrets.BLOCKCHAIN_PROVIDER_URL }}
          REGISTRY_CONTRACT_ADDRESS: ${{ secrets.REGISTRY_CONTRACT_ADDRESS }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          API_KEY: ${{ secrets.APY_KEY }}
        run: npx hardhat run scripts/proof-verification.ts
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled

    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_PROD_WEBHOOK }}
          title: '${{ github.workflow }}: {{STATUS}}'
          description: '${{ github.event_name }} trigged this {{STATUS}}!'
          # include-details: 'false'